name: 露天自動打卡

on:
  workflow_dispatch: ~
  schedule:
    - cron:  '1 16 * * *'

jobs:        
  line-notify:
    name: Ruten check-in
    runs-on: ubuntu-latest
    env:
      ACCOUNT: ${{ secrets.ACCOUNT }}
      PASSWORD: ${{ secrets.PASSWORD }}
      LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
    steps:      
      - name: Check config
        if: ${{ github.event_name == 'workflow_dispatch' }}        
        run: |
          exit_code=0
          if [[ -z "$ACCOUNT" ]]; then
            echo '::error::你沒有設定ACCOUNT 帳號，請再確認一次。'
            exit_code=87
          fi

          if [[ -z "$PASSWORD" ]]; then
            echo '::error::你沒有設定PASSWORD 密碼，請再確認一次。'
            exit_code=87
          fi

          if [[ -z "$LINE_NOTIFY_TOKEN" ]]; then
            echo '::error::你沒有設定LINE_NOTIFY_TOKEN 權杖，請再確認一次。'
            exit_code=87
          fi                 

          exit $exit_code

      - name: Check out code
        uses: actions/checkout@v3

      - name: Create docker container
        run: |
          docker run --rm --privileged -e ACCOUNT=${{ env.ACCOUNT }} -e PASSWORD=${{ env.PASSWORD }} -e LINE_NOTIFY_TOKEN=${{ env.LINE_NOTIFY_TOKEN }}  evanhongo/ruten-check-in:v1.0.0